# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.match_int_C <- function(ls1, v2, incomparables) {
    .Call('_anRichment_match_int_C', PACKAGE = 'anRichment', ls1, v2, incomparables)
}

.intersect_int <- function(ls1, v2, incomparables) {
    .Call('_anRichment_intersect_int', PACKAGE = 'anRichment', ls1, v2, incomparables)
}

.intersectSize_int <- function(ls1, v2, incomparables) {
    .Call('_anRichment_intersectSize_int', PACKAGE = 'anRichment', ls1, v2, incomparables)
}

.intersectSizesForEnrichment <- function(classes, classBg, class2bg, refSets, doMap, class2ref, class2setIDHasDuplicates, bgTypeR, mappedRefBg, returnMappedSets) {
    .Call('_anRichment_intersectSizesForEnrichment', PACKAGE = 'anRichment', classes, classBg, class2bg, refSets, doMap, class2ref, class2setIDHasDuplicates, bgTypeR, mappedRefBg, returnMappedSets)
}

